<?php
/**
 * GN2_Devito
 *
 * @category GN2_Devito
 * @package  GN2_Devito
 * @author   Christoph Stäblein <cs@gn2-netwerk.de>
 * @author   Dave Holloway <dh@gn2-netwerk.de>
 * @license  GNU General Public License, version 2 http://www.gnu.org/licenses/old-licenses/gpl-2.0.html
 * @version  Release: <package_version>
 * @link     http://www.gn2-netwerk.de
 */

/**
 * Smarty function to redirect calls through
 * TimThumb.
 *
 * @param array  $params  Devito settings
 * @param Smarty &$smarty Smarty reference
 *
 * @example [{devito src=$sourceUrl preset="details"}]
 * @example [{devito src=$sourceUrl settings="w:738;h:464;zc:2;"}]
 *
 * @return string Modified string
 */
function Smarty_Function_Devito($params, &$smarty)
{
    $oViewConf = oxNew('oxviewconfig');

    /* If no source, set to '' */
    $src = (isset($params['src'])) ? str_replace($oViewConf->getBaseDir(), '', $params['src']) : '';

    /* If picture isn't generated by oxid, try to make it happen :) */
    if (!file_exists($src)) {
        if (function_exists('curl_init')) {
            $ch = curl_init($params['src']);
            curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
            curl_setopt($ch, CURLOPT_HEADER, 0);
            $data = curl_exec($ch);
            curl_close($ch);
        }
    }

    /* If possible, load presets from presets.php */
    if (isset($params['preset'])) {
        if (array_key_exists($params['preset'], GN2_Devito_Tools::$presets)) {
            $params['settings'] = GN2_Devito_Tools::$presets[$params['preset']];
        }
    }

    /* Parse settings into a usable form. */
    $settings = array();
    if (isset($params['settings']) && $src !== '') {
        $tmpSettings = explode(';', $params['settings']);
        foreach ($tmpSettings as $row) {
            $setting = explode(':', $row, 2);
            if (count($setting) == 2) {
                $key = trim($setting[0]);
                $value = trim($setting[1]);
                if ($key != '' && $value != '' && $key!='preset') {
                    $settings[$key] = $value;
                }
            }
        }
        $settings['src'] = $src;

        /* Generate the devito url to resize the image */
        $src = $oViewConf->getBaseDir().'?devito&amp;'.http_build_query($settings, '&amp;');
    }
    return $src;
}
